import { Metadata } from "next";
import "./global.css";
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "red", padding: "1rem" }}>Header</header>
        {children}
        <footer style={{ backgroundColor: "orange", padding: "1rem" }}>Footer</footer>
      </body>
    </html>
  );
}
